# This workflow will run a Python file that will send a tweet every time an issue is labeled a good first issue.

name: Run Python file that sends a tweet

on:
  issues:
    types: [labeled]
    
jobs:
  sendGoodFirstIssueTweet:
    if:  github.event.label.name == 'good first issue'
    runs-on: 'ubuntu-latest'
    env:
      Issue: https://github.com/${{ github.actor }}/${{ github.event.repository.name }}/issues/${{ github.event.issue.number }} 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: | 
          pip3 install tweepy
          python3 randomfile.py ${{ secrets.CONSUMER_KEY }} ${{ secrets.CONSUMER_SECRET }} ${{ secrets.ACCESS_TOKEN }} ${{ secrets.ACCESS_TOKEN_SECRET }} $Issue

